### ISSUE TITLE
stream-read-ucs-string returns empty string

### ISSUE THREAD

**Issue by faeredia** [mv2devnul/taglib#1]
audio-streams:stream-read-ucs-string incorrectly returns "", despite len being greater than 0.

Line 195 in audio-streams.lisp should be:
`(when (<= len 0)
  (return-from stream-read-ucs-string ""))`
instead of:
`(when (<= 0 len)
  (return-from stream-read-ucs-string ""))`

**Comment by mv2devnul** [comment]
Thanks for the fix!
